baseURL = 'https://free.sudoshz.ir'
languageCode = 'fa'
title = 'جنبش نرم‌افزار آزاد'
theme = ["github.com/onweru/compose"]
rssLimit = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]

[languages]
  [languages.en]
    title = 'Write Free Software'
    languageName = 'English'
    weight = 1
  [languages.zh-cn]
    title = '编写自由软件'
    languageName = '简体中文'
    weight = 1
  [languages.id]
    title = 'Membuat Free Software'
    languageName = 'Bahasa Indonesia'
    weight = 1
