baseURL = 'https://writefreesoftware.org'
languageCode = 'en-US'
title = 'Write Free Software'
theme = ["github.com/onweru/compose"]
rssLimit = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]

[languages]
  [languages.en]
    title = 'Write Free Software'
    languageName = 'English'
    weight = 1
  [languages.fr]
    title = 'Écrire un logiciel libre'
    languageName = 'Français'
    weight = 1
