[[main]]
  name = "Learn"
  weight = 2
  url = "learn/"

[[main]]
  name = "Community"
  weight = 5
  url = "https://discourse.writefreesoftware.org"

[[main]]
  name = "Blog"
  weight = 5
  url = "blog/"
